groups:
- name: webapp_alerts
  rules:
  - alert: HighP95Latency
    expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le)) > 1
    for: 5m
    labels:
      severity: page
    annotations:
      summary: "High p95 latency (>1s) for 5m"
  - alert: HighErrorRate
    expr: sum(rate(http_requests_total{status=~\"5..\"}[5m])) / sum(rate(http_requests_total[5m])) > 0.02
    for: 3m
    labels:
      severity: page
    annotations:
      summary: "High 5xx error rate (>2%)"
